[[dependents]]
repository = "https://github.com/ethereum/trio-run-in-process"
toxenv_glob = "*"

[[dependents]]
repository = "https://github.com/python-trio/snekomatic"
toxenv_glob = "*"


[[dependents]]
repository = "https://github.com/Azure/msrest-for-python"
toxenv_glob = "*"
